### ISSUE TITLE
java.lang.IllegalArgumentException: Name and ID cannot both be blank in GameProfile

### ISSUE THREAD

**Issue by Entoarox** [TheTemportalist/ThaumicExpansion#9]
java.lang.IllegalArgumentException: Name and ID cannot both be blank in GameProfile
    at com.temportalist.thaumicexpansion.common.tile.TEAnalyzer.setMode(TEAnalyzer.scala:126)
    at com.temportalist.thaumicexpansion.common.block.BlockAnalyzer.func_149689_a(BlockAnalyzer.scala:53)
    at net.minecraft.item.ItemBlock.placeBlockAt(ItemBlock.java:213)
    at net.minecraft.item.ItemBlock.func_77648_a(ItemBlock.java:103)
    at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:129)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:360)
    at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1447)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1953)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
    at org.multimc.EntryPoint.listen(EntryPoint.java:170)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)

Happens upon trying to place the analyzer.

**Comment by anishin** [comment]
@TheTemportalist !
You should change expression in 'if' and 'else' statements.
Now it cause exception, because in 'else' statement you don't specify any expression:

```
                if (id == null && p.getGameProfile.getName != null)
                    id = UUID.fromString(p.getGameProfile.getName)
                else /* if (id != null || p.getGameProfile.getName == null) */ throw new IllegalArgumentException(
                    "Name and ID cannot both be blank in GameProfile")

```

You should make it like so:

```
                if (p.getGameProfile.getId != null)
                    id = p.getGameProfile.getID
                else if (p.getGameProfile.getName != null)
                    id = UUID.fromString(p.getGameProfile.getName)
                else  throw new IllegalArgumentException(
                    "Name and ID cannot both be blank in GameProfile")
```

Please, fix this issue! It breaks all functionalof this awesome mod!

P. S. Sorry for my English. I'm from Russia.
P. P. S. Sorry for my Scala. I'm working on Java)))

**Comment by TheTemportalist** [comment]
So I actually ended up changing this. https://github.com/TheTemportalist/ThaumicExpansion/blob/master/src/main/scala/com/temportalist/thaumicexpansion/common/item/ItemMode.scala#L79

``` scala
            var id = player.getGameProfile.getId
            val name = player.getGameProfile.getName

            if (id == null) {
                if (name != null) id = Players.usernameToId.get(name)
                else Players.message(player,
                    "ID and Name of your GameProfile are null. Report this to mod author.")
            }
            if (id != null) {
                val copy: ItemStack = stack.copy()
                this.setUUID(copy, player.getGameProfile.getId)
                copy.getTagCompound.setString("name", name)
                player.setCurrentItemOrArmor(0, copy)
            }
```

If you take a looksee there, I ended up going with just checking if it worked or not. For the most part, this was being thrown somewhere else because the client and server were not being synced. This should not longer be a problem.
